### ISSUE TITLE
builds from master broken since #4005

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra#4029]
extracted from https://github.com/georchestra/georchestra/pull/4028#issuecomment-1708292492 and also experienced on the community buildbot:
```
[ERROR] /var/lib/buildbot/workers/georchestra/buildjob-master/build/security-proxy-spring-integration/src/main/java/org/georchestra/security/client/console/GeorchestraConsoleUsersApiImpl.java:[35,8] org.georchestra.security.client.console.GeorchestraConsoleUsersApiImpl is not abstract and does not override abstract method findByOAuth2ProviderId(java.lang.String) in org.georchestra.security.api.UsersApi
```

for the buildbot, the build failure happens since https://github.com/georchestra/georchestra/commit/f5f65f1f0ac462148364f37ae7382da29f98d3e0 from #4005

**Comment by landryb** [comment]
while #4037 is still open, the build issue itself was fixed by #4042
