### ISSUE TITLE
CAS doesn't work with Spring 4

### ISSUE THREAD

**Issue by groldan** [georchestra/georchestra#2492]
CAS compiles but won't start with Spring 4.
Need to apply #2491 (fix for #2461) before, otherwise the spring config error will show up before.

The `org.jasig.cas:*:4.0.0` dependencies we're using seem to be just too old ([May 2014](https://mvnrepository.com/artifact/org.jasig.cas/cas-server-core/4.0.0)) and moved from the `org.jasig.cas` namespace to [org.apereo.cas](https://mvnrepository.com/artifact/org.apereo.cas/cas-server-core).

I'm afraid this might not be just a trivial dependency upgrade though and blocks 18.12. Sigh.

@fvanderbiest @pmauduit @severo shall we panic? I think I'm hyperventilating already. It doesn't help that the cas module has no tests at all, guess we should at the very least add some smoke tests to make sure the app starts up and listens.

**Comment by groldan** [comment]
ah, forgot to mention which errors it's throwing:

```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean]: No default constructor found; nested exception is java.lang.NoClassDefFoundError: org/quartz/impl/JobDetailImpl
    at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate (SimpleInstantiationStrategy.java:85)
....
    at org.jasig.cas.web.init.SafeContextLoaderListener.contextInitialized (SafeContextLoaderListener.java:75)
....
Caused by: java.lang.NoClassDefFoundError: org/quartz/impl/JobDetailImpl
    at java.lang.Class.getDeclaredConstructors0 (Native Method)
    at java.lang.Class.privateGetDeclaredConstructors (Class.java:2671)
    at java.lang.Class.getConstructor0 (Class.java:3075)
    at java.lang.Class.getDeclaredConstructor (Class.java:2178)
    at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate (SimpleInstantiationStrategy.java:80)
....
    at org.jasig.cas.web.init.SafeContextLoaderListener.contextInitialized (SafeContextLoaderListener.java:75)

```

**Comment by severo** [comment]
Maybe we should revert the removal of Spring version numbers, at least for CAS, for 18.12, and then work on upgrading CAS for 19.06.

**Comment by fvanderbiest** [comment]
> Maybe we should revert the removal of Spring version numbers, at least for CAS, for 18.12,

Yes, let's use an older Spring version for CAS on `18.12`.
The upgrade will be done for `19.06`, which leaves us some time...

**Comment by fvanderbiest** [comment]
As a result I'm sure #2491 is useful anymore.

**Comment by fvanderbiest** [comment]
> guess we should at the very least add some smoke tests to make sure the app starts up and listens.

+1

**Comment by groldan** [comment]
> As a result I'm not sure #2491 is useful anymore.
I'd say yes, it doesn't hurt and is future proof.

**Comment by groldan** [comment]
Fixed by #2492

**Comment by severo** [comment]
Fixed by #2515  :-)
