### ISSUE TITLE
[geoserver] broken startup in stable when not using docker/jetty

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra#3358]
this was discussed in #3094 but was never fixed in the doc or in the ansible playbook, so a deployment of 20.0.x or 20.1.x using one of those methods will miserably fail when starting geoserver with CORS enabled:
```
20-Apr-2021 08:06:47.121 GRAVE [Catalina-utility-2] org.apache.catalina.core.StandardContext.filterStart Exception au démarrage du filtre [cross-origin]
        java.lang.ClassNotFoundException: org.eclipse.jetty.servlets.CrossOriginFilter
```

so yeah, somewhere, something has to be done so that 'jetty-servlets' (or whatever that is) are present somewhere ?

**Comment by landryb** [comment]
regression caused by #3084 which only took care of the docker case.

**Comment by landryb** [comment]
fetching jetty-servlets jar into `geoserver/WEB-INF/lib` isnt enough to fix the startup failure:
```
<2>Caused by: org.apache.catalina.LifecycleException: Echec de démarrage du composant [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/geoserver]]
<2>    at org.apache.catalina.util.LifecycleBase.handleSubClassException(LifecycleBase.java:440)
<2>    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:198)
<2>    at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:717)
<2>    ... 37 more
<2>Caused by: java.lang.NoClassDefFoundError: Lorg/eclipse/jetty/util/log/Logger;
```

**Comment by landryb** [comment]
so to have gs working again, one needs (thanks @pmauduit):
- https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-servlets/9.4.40.v20210413/jetty-servlets-9.4.40.v20210413.jar
- https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-continuation/9.4.40.v20210413/jetty-continuation-9.4.40.v20210413.jar
- https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-http/9.4.40.v20210413/jetty-http-9.4.40.v20210413.jar
- https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-util/9.4.40.v20210413/jetty-util-9.4.40.v20210413.jar
- https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-io/9.4.40.v20210413/jetty-io-9.4.40.v20210413.jar

fetched into `geoserver/WEB-INF/lib` to restore a working geoserver.

as advised in https://github.com/georchestra/georchestra/pull/3094#issuecomment-653018614 the simplest fix would be to add the jetty-servlets dependency in the geoserver pom.xml file and backport that to 20.0.x and 20.1.x branches which are currently broken.

**Comment by pmauduit** [comment]
in 2.18.x versions of GS, it seems that the web.xml now suggests 2 different configurations for jetty or tomcat:

```
   <!-- Uncomment following filter to enable CORS in Jetty. Do not forget the second config block further down.
    <filter>
      <filter-name>cross-origin</filter-name>
      <filter-class>org.eclipse.jetty.servlets.CrossOriginFilter</filter-class>
      <init-param>
        <param-name>chainPreflight</param-name>
        <param-value>false</param-value>
      </init-param>
      <init-param>
        <param-name>allowedOrigins</param-name>
        <param-value>*</param-value>
      </init-param>
      <init-param>
        <param-name>allowedMethods</param-name>
        <param-value>GET,POST,PUT,DELETE,HEAD,OPTIONS</param-value>
      </init-param>
      <init-param>
        <param-name>allowedHeaders</param-name>
        <param-value>*</param-value>
      </init-param>
    </filter>
     -->
   <!-- Uncomment following filter to enable CORS in Tomcat. Do not forget the second config block further down. -->
    <filter>
      <filter-name>cross-origin</filter-name>
      <filter-class>org.apache.catalina.filters.CorsFilter</filter-class>
      <init-param>
        <param-name>cors.allowed.origins</param-name>
        <param-value>*</param-value>
      </init-param>
      <init-param>
        <param-name>cors.allowed.methods</param-name>
        <param-value>GET,POST,PUT,DELETE,HEAD,OPTIONS</param-value>
      </init-param>
      <init-param>
        <param-name>cors.allowed.headers</param-name>
        <param-value>*</param-value>
      </init-param>
    </filter>
```

Main issue is by default bot filters are defined ... which makes the webapp unable to boot with the following error:

```
org.xml.sax.SAXParseException; systemId: [...]; lineNumber: 211; columnNumber: 14; Error at line [211] column [14]: [Duplicate filter name [cross-origin]]
```

This comes from the geoserver submodule's suggested web.xml: https://github.com/georchestra/geoserver/blob/c84d965361a94af44f413a1ab3a2e38518eaf8bf/src/web/app/src/main/webapp/WEB-INF/web.xml#L173-L211

Docker setups are unaffected because they override the web.xml in the image at build time.

I'd suggest to update the submodule after having commented out the filter. It should be pretty straightforward to uncomment one or the other depending on one's own setup (but for now, we can't determine at build time in which servlet container the produced GS will be deployed ...).

**Comment by fvanderbiest** [comment]
> I'd suggest to update the submodule after having commented out the filter. It should be pretty straightforward to uncomment one or the other depending on one's own setup (but for now, we can't determine at build time in which servlet container the produced GS will be deployed ...).

What a nightmare...
Can we be consistent and suppose that standard deploys rely on tomcat (as advised on our documentation) ? ...

**Comment by fvanderbiest** [comment]
> having the tomcat bit uncommented, with a comment in web.xml for jetty setups would be the best choice

agreed

**Comment by landryb** [comment]
i dont see how this georchestra/ansible@5dcb040f6a06665079a81b64db917c4afa336921 fixes this issue :D

**Comment by landryb** [comment]
in this issue, what i dont understand is how come the `webapp/src/docker/web.xml` (from 699b1e03) gets installed/shipped in the war/used in the non-docker setup... i guess maven mystery.

**Comment by landryb** [comment]
or the problem is actually in the geoserver submodule ? i think georchestra/geoserver@9b1e38bb5 (which percolated to 2.17.5 (which is what im testing on) in georchestra/geoserver@b67db20) uncomments the jetty case CORS setup, without commenting the tomcat case.

**Comment by pmauduit** [comment]
> i dont see how this georchestra/ansible@5dcb040f6a06665079a81b64db917c4afa336921 fixes this issue :D

It doesn't ; i mentionned the issue in a commit and github thought it was fixing it while merging. I confirm I haven't done anything yet to fix it.

The web.xml from the submodule is broken but I think this has been fixed in the next upstream geoserver versions (by fixing I mean both filters commented out, not the resolution stated in this issue - keeping the tomcat one activated).

**Comment by jeanpommier** [comment]
It seems that the best way would be to keep both commented by default (have an agnostic war file that can deploy on any solution)
And uncomment/override the web.xml on deployment, when using Ansible, docker or whatever.
What do you think ?
