### PR TITLE
use commons-httpclient from atlassian fork to fix #2183

### LINKED ISSUE #2183: [mfprint] fix printing with https layers over SNI
Comeback of bug #1313 but this time for mapfishapp..

mfprint uses  `commons-httpclient-3.1.jar` which is dead upstream and doesnt support SNI. 

I faced crashes when printing layers coming from https servers with SNI, so i digged out an alternative source for this jar maintained by atlassian that supports SNI, cf https://bitbucket.org/atlassian/apache-httpclient-3.x/commits/tag/commons-httpclient-3.1-atlassian-2

- using their jar fixed the issue for me.

### PR DESCRIPTION
**Pull request by landryb**
commons-httpclient is dead upstream and doesnt support SNI,
the atlassian fork added support for it and that fixes mapfishapp
printing https layers served by servers using a cert with SNI.

With this pom.xml bit, the right jar is shipped in the war:
```
-rw-r--r-- 1 landry users 313907 Feb 11 09:33 /home/landry/.m2/repository/commons-httpclient/commons-httpclient/3.1-atlassian-2/commons-httpclient-3.1-atlassian-2.jar
-rw-r--r-- 1 landry users 305001 Sep 11  2017 /home/landry/.m2/repository/commons-httpclient/commons-httpclient/3.1/commons-httpclient-3.1.jar
...
$unzip -l mapfishapp/target/mapfishapp-generic.war |grep commons-http
   313907  2019-02-11 09:33   WEB-INF/lib/commons-httpclient-3.1-atlassian-2.jar

```
PR targetting master but nice to have in 18.12.

For some reason here on my throwaway/testing instance mfapp tells me that the print service isnt available (there's a NPE when hitting `/mapfishapp/pdf`) so i cant really test it, but i've been using this jar in production for the past 6 months.

### CODE REVIEW

**Comment by landryb** [comment]
same npe with the default jar, so its' probably a local issue with datadir merging or smth. 
```
java.lang.NullPointerException
	org.mapfish.print.servlet.MapPrinterServlet.doGet(MapPrinterServlet.java:91)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	org.tuckey.web.filters.urlrewrite.NormalRewrittenUrl.doRewrite(NormalRewrittenUrl.java:195)
	org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:159)
	org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:141)
	org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:90)
	org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:406)
```
shouldnt prevent testing from others :)

**Comment by fvanderbiest** [comment]
Tested on my side:
```
mapfishapp_1                | 2019-02-12 13:08:14.270:WARN:oejs.HttpChannel:qtp1639622804-36: /mapfishapp/pdf/info.json
mapfishapp_1                | java.lang.NoSuchMethodError: org.json.JSONWriter.<init>(Ljava/io/Writer;)V
mapfishapp_1                | 	at org.mapfish.print.servlet.MapPrinterServlet.getInfo(MapPrinterServlet.java:289)
mapfishapp_1                | 	at org.mapfish.print.servlet.MapPrinterServlet.doGet(MapPrinterServlet.java:99)
```

**Comment by fvanderbiest** [comment]
> But it does not seem related

I can confirm this is another issue: #2493

**Comment by landryb** [comment]
Thanks for testing it - was a bit concerned this would have broken printing.. i know this jar works on 18.06, its just that i've replaced the 'standard' commons-httpclient jar with it on my production systems (ie it doesnt have the `-atlassian-2` suffix)

**Comment by fvanderbiest** [comment]
When used in conjunction with 9afdea2d687739bd025e1628a998b64b84709937:

[ERROR] Failed to execute goal on project mapfishapp: Could not resolve dependencies for project org.georchestra:mapfishapp:war:19.06-SNAPSHOT: Could not find artifact commons-httpclient:commons-httpclient:jar:3.1-atlassian-2 in artifactory-georchestra (https://packages.georchestra.org/artifactory/maven) -> [Help 1]

Else it builds and works fine !

**Comment by landryb** [comment]
i suppose artifactory needs to be updated somehow with new deps declared in pom files ? @pmauduit ?

**Comment by fvanderbiest** [comment]
Backported to 18.12 with 593a6f40b

**Comment by pmauduit** [comment]
> i suppose artifactory needs to be updated somehow with new deps declared in pom files ? @pmauduit ?

Done
